controller:
  admin:
    username: ${admin_user}
    password: ${admin_password}

  containerEnv:
    - name: ECR_REPOSITORY_URL
      value: "${ecr_repository_url}"
    - name: AWS_REGION
      value: "${aws_region}"

  serviceType: ${service_type}
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - pipeline-stage-view:latest
    - docker-workflow:latest
    - workflow-multibranch:latest
    - amazon-ecr:latest

persistence:
  enabled: true
  storageClass: "${storage_class}"
  size: "10Gi"
