{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
    path: {{ .source.path }}
    helm:
      {{- if .source.helm }}
      {{- if .source.helm.values }}
      values: |
{{ .source.helm.values | indent 8 }}
      {{- end }}
      {{- end }}

  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: django-app-django-app-secret
      jsonPointers:
        - /data
        - /stringData

  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune | default true }}
      selfHeal: {{ .syncPolicy.automated.selfHeal | default true }}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
